/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    // Use jitpack for processing-core-4
    maven {
      url = uri("https://jitpack.io")
    }
    // Use jogamp for jogl
    maven {
      url = uri("https://jogamp.org/deployment/maven/")
    }
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")
    implementation("com.github.micycle1:processing-core-4:4.3")

    // // file dependencies
    // implementation(files("libs/processing.jar"))
}

application {
    // Define the main class for the application.
    mainClass.set("musubi.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
